# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordsofqiu',
            name='author',
        ),
    ]
